### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by dmxd5** [feimosi/baguetteBox.js#223]
After a recent Chrome update, the following error began occurring on mobile swipe:

> Unable to preventDefault inside passive event listener invocation.
> touchmoveHandler @ baguetteBox.js:107

**Comment by zalevsk1y** [comment]
[Google](https://developers.google.com/web/updates/2017/01/scrolling-intervention) changed the default behavior of touch listeners, now they are passive. The same thing in iOS/Safari since version 11.3. And as [Google explains](https://developers.google.com/web/updates/2019/02/scrolling-intervention):
> Registering the event listeners as passive tells the browser that the listeners will not call preventDefault() and the browser can safely perform scrolling and zooming without blocking on the listeners.
So you cannot call preventDefault inside passive event listener.
Solutions: 
- Set css property `touch-action:none` to body. Not supported by iOS/Safari.
- Set passive property to false.
`var options = supports.passiveEvents ? { passive: false } : null;  `

**Comment by feimosi** [comment]
Fixed in v1.11.1
