### ISSUE TITLE
Customize SVG buttons

### ISSUE THREAD

**Issue by PaulM75** [feimosi/baguetteBox.js#35]
Hi, how can i customize buttons/arrows? Ths

**Comment by feimosi** [comment]
It's impossible with CSS as they're hardcoded as SVG in the .js file. You can always change the color by modifying that file, but it's just a workaround. Implementing buttons customization would be too complicated.

**Comment by mattweb** [comment]
Hey Marek,

I'm also interested in customizing buttons. Wouldn't this be a simple solution?
https://flickity.metafizzy.co/options.html#arrowshape

Thanks for your good work!
Matt

**Comment by Mushr0000m** [comment]
Yes it would be nice to be able with CSS to at least change the color of the stroke.

**Comment by joshangehr** [comment]
@Mushr0000m You can change the stroke colour with this CSS:

```
polyline, line {
    stroke: red;
}
```

As for the custom SVG icons, I see that the [previous pull request](https://github.com/feimosi/baguetteBox.js/pull/204) looks to been abandoned. @feimosi I can whip up a new one if you're still taking contributions? I've done it with very minimal changes (essentially just passing the `userOptions` to the `buildOverlay()` function so that we can access custom values, and then updating the `innerHTML` of each icon if one exists.

**Comment by feimosi** [comment]
@joshangehr sure :+1:

**Comment by crafted-at** [comment]
> [...] I see that the previous pull request looks to been abandoned. @feimosi I can whip up a new one if you're still taking contributions? 

@joshangehr are you still pursuing this?

**Comment by feimosi** [comment]
For anyone subscribed to this thread, this functionality has just been released based on #245
